package com.gym.service;

import com.gym.dao.UserDAO;
import com.gym.model.Member;
import com.gym.model.User;
import java.util.*;

/**
 * RegistrationService - Handles user registration business logic
 */
public class RegistrationService {

    private UserDAO userDAO;
    private PasswordService passwordService;
    private MemberService memberService;

    public RegistrationService() {
        this.userDAO = new UserDAO();
        this.passwordService = new PasswordService();
        this.memberService = new MemberService();
    }

    /**
     * Register a new user
     * @param request Registration request data
     * @return Registration result
     */
    public RegisterResult register(RegisterRequest request) {
        RegisterResult result = new RegisterResult();
        List<String> errors = new ArrayList<>();

        // Validate input
        validateInput(request, errors);
        
        if (!errors.isEmpty()) {
            result.setSuccess(false);
            result.setErrors(errors);
            return result;
        }

        // Check for duplicates
        if (userDAO.existsByUsername(request.getUsername())) {
            errors.add("Tên đăng nhập đã tồn tại");
        }
        
        if (userDAO.existsByEmail(request.getEmail())) {
            errors.add("Email đã được sử dụng");
        }

        if (!errors.isEmpty()) {
            result.setSuccess(false);
            result.setErrors(errors);
            return result;
        }

        // Hash password
        String passwordHash = passwordService.hashPassword(request.getPassword());
        // Note: salt is not stored in User entity, it's handled by PasswordService

        // Get and trim name (full name)
        String name = (request.getName() != null) ? request.getName().trim() : null;
        System.out.println("[RegistrationService] Registering user:");
        System.out.println("  - Username: " + request.getUsername());
        System.out.println("  - Name (full name): " + name);
        System.out.println("  - Email: " + request.getEmail());

        // IMPORTANT: Create Member directly (not User) because Member extends User
        // This ensures JPA JOINED inheritance works correctly:
        // 1. JPA will create ONE record in user table with DTYPE='MEMBER'
        // 2. JPA will create ONE record in members table with same user_id
        // This prevents duplicate user_id issues
        Member member = new Member();
        member.setUsername(request.getUsername());
        member.setName(name);
        member.setEmail(request.getEmail());
        member.setPassword(passwordHash);
        member.setStatus("ACTIVE");
        member.setCreatedDate(java.time.LocalDateTime.now());
        // Note: updatedDate will be set automatically by @PreUpdate if needed
        
        // Member-specific fields will be null initially
        // User can update them later via Dashboard
        
        // Save Member - this will create both User and Member records with same user_id
        // IMPORTANT: userId will be NULL initially, then generated by database during persist()
        long userId = -1;
        try {
            System.out.println("[RegistrationService] ========================================");
            System.out.println("[RegistrationService] BEFORE saveProfile - userId: " + member.getUserId());
            System.out.println("[RegistrationService] Creating Member entity (which extends User)...");
            
            // Call saveProfile - this will:
            // 1. Call MemberDAO.upsert()
            // 2. MemberDAO.upsert() will call em.persist(member)
            // 3. em.flush() will execute INSERT and MySQL generates user_id
            // 4. em.refresh() will reload entity with generated user_id
            memberService.saveMember(member);
            
            // Get the generated user_id AFTER save
            System.out.println("[RegistrationService] AFTER saveProfile - userId: " + member.getUserId());
            
            if (member.getUserId() != null) {
                userId = member.getUserId().longValue();
                System.out.println("[RegistrationService] ✓ SUCCESS: Member created with user_id: " + userId);
            } else {
                System.err.println("[RegistrationService] WARNING: userId is still null after saveProfile!");
                System.err.println("[RegistrationService] Trying to find user by email as fallback...");
                // If userId not set, try to find by email (fallback)
                User foundUser = userDAO.findByEmail(request.getEmail());
                if (foundUser != null) {
                    userId = foundUser.getId();
                    System.out.println("[RegistrationService] Found user_id from database: " + userId);
                    // Update member object with found userId
                    member.setUserId((int) userId);
                }
            }
            System.out.println("[RegistrationService] ========================================");
        } catch (Exception e) {
            System.err.println("[RegistrationService] ERROR creating Member: " + e.getMessage());
            e.printStackTrace();
            result.setSuccess(false);
            result.setErrors(Arrays.asList("Lỗi hệ thống khi tạo tài khoản: " + e.getMessage()));
            return result;
        }

        if (userId == -1) {
            result.setSuccess(false);
            result.setErrors(Arrays.asList("Lỗi hệ thống khi tạo tài khoản"));
            return result;
        }
        
        // Verify user/member was created
        User createdUser = userDAO.getUserById(userId);
        if (createdUser == null) {
            createdUser = userDAO.findByEmail(request.getEmail());
            if (createdUser == null) {
                result.setSuccess(false);
                result.setErrors(Arrays.asList("Lỗi hệ thống: Tài khoản đã được tạo nhưng không thể tải thông tin. Vui lòng thử đăng nhập."));
                return result;
            }
            userId = createdUser.getId();
        }
        
        System.out.println("[RegistrationService] User/Member loaded successfully:");
        System.out.println("  - User ID: " + userId);
        System.out.println("  - Username: " + createdUser.getUsername());
        System.out.println("  - Name: " + createdUser.getName());
        System.out.println("  - Email: " + createdUser.getEmail());
        System.out.println("  - Class: " + createdUser.getClass().getSimpleName());

        // ✅ Set user.role column to "MEMBER" for new registrations
        createdUser.setRole("MEMBER");
        try {
            userDAO.update(createdUser);
            System.out.println("[RegistrationService] Successfully set role='MEMBER' for user_id: " + userId);
        } catch (Exception e) {
            System.err.println("[RegistrationService] ERROR setting role: " + e.getMessage());
            e.printStackTrace();
        }

        // Log registration
        userDAO.insertLoginHistory(userId, request.getIpAddress(), request.getUserAgent());
        
        result.setSuccess(true);
        result.setMessage("Đăng ký thành công! Bạn có thể đăng nhập ngay bây giờ.");
        result.setUserId(userId);

        return result;
    }

    /**
     * Validate registration input
     */
    private void validateInput(RegisterRequest request, List<String> errors) {
        if (request.getUsername() == null || request.getUsername().trim().isEmpty()) {
            errors.add("Tên đăng nhập không được để trống");
        } else if (request.getUsername().length() < 3) {
            errors.add("Tên đăng nhập phải có ít nhất 3 ký tự");
        } else if (!request.getUsername().matches("^[a-zA-Z0-9_]+$")) {
            errors.add("Tên đăng nhập chỉ được chứa chữ cái, số và dấu gạch dưới");
        }

        if (request.getName() == null || request.getName().trim().isEmpty()) {
            errors.add("Tên đầy đủ không được để trống");
        } else if (request.getName().trim().length() < 2) {
            errors.add("Tên đầy đủ phải có ít nhất 2 ký tự");
        }

        if (request.getEmail() == null || request.getEmail().trim().isEmpty()) {
            errors.add("Email không được để trống");
        } else if (!isValidEmail(request.getEmail())) {
            errors.add("Email không hợp lệ");
        }

        if (request.getPassword() == null || request.getPassword().trim().isEmpty()) {
            errors.add("Mật khẩu không được để trống");
        } else {
            String passwordError = passwordService.getPasswordValidationMessage(request.getPassword());
            if (passwordError != null) {
                errors.add(passwordError);
            }
        }

        if (request.getConfirmPassword() == null || request.getConfirmPassword().trim().isEmpty()) {
            errors.add("Xác nhận mật khẩu không được để trống");
        } else if (!request.getPassword().equals(request.getConfirmPassword())) {
            errors.add("Mật khẩu và xác nhận mật khẩu không khớp");
        }
    }

    /**
     * Simple email validation
     */
    private boolean isValidEmail(String email) {
        return email.matches("^[A-Za-z0-9+_.-]+@([A-Za-z0-9.-]+\\.[A-Za-z]{2,})$");
    }

    /**
     * Registration request DTO
     */
    public static class RegisterRequest {
        private String username;
        private String name;  // Full name
        private String email;
        private String password;
        private String confirmPassword;
        private String ipAddress;
        private String userAgent;

        // Constructors
        public RegisterRequest() {}

        public RegisterRequest(String username, String name, String email, String password, String confirmPassword) {
            this.username = username;
            this.name = name;
            this.email = email;
            this.password = password;
            this.confirmPassword = confirmPassword;
        }

        // Getters and Setters
        public String getUsername() { return username; }
        public void setUsername(String username) { this.username = username; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }

        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }

        public String getConfirmPassword() { return confirmPassword; }
        public void setConfirmPassword(String confirmPassword) { this.confirmPassword = confirmPassword; }

        public String getIpAddress() { return ipAddress; }
        public void setIpAddress(String ipAddress) { this.ipAddress = ipAddress; }

        public String getUserAgent() { return userAgent; }
        public void setUserAgent(String userAgent) { this.userAgent = userAgent; }
    }

    /**
     * Registration result DTO
     */
    public static class RegisterResult {
        private boolean success;
        private String message;
        private long userId;
        private List<String> errors;

        public RegisterResult() {
            this.errors = new ArrayList<>();
        }

        // Getters and Setters
        public boolean isSuccess() { return success; }
        public void setSuccess(boolean success) { this.success = success; }

        public String getMessage() { return message; }
        public void setMessage(String message) { this.message = message; }

        public long getUserId() { return userId; }
        public void setUserId(long userId) { this.userId = userId; }

        public List<String> getErrors() { return errors; }
        public void setErrors(List<String> errors) { this.errors = errors; }
    }
}
